int a = 7;
int b = 4;
int c = 3;
int d = (a + b) / c;
int e = (a + b) % c;
Console.WriteLine($"Quotient: {d}");
Console.WriteLine($"Remainder: {e}");
int max = int.MaxValue;
int min = int.MinValue;
Console.WriteLine($"Range of Integers is {min} to {max}");
